package kr.co.easymanual;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;

public class Test {

	public static void main(String[] args) {
		Map<String, String> map = new HashMap<String, String>();

        map.put("aa-DJ", "Djibouti");
        map.put("aa-ER", "Eritrea");
        map.put("aa-ET", "Ethiopia");
        map.put("af-ZA", "South Africa");
        map.put("am-ET", "Ethiopia");
        map.put("an-ES", "Spain");
        map.put("ar-AE", "United Arab Emirates");
        map.put("ar-BH", "Bahrain");
        map.put("ar-DZ", "Algeria");
        map.put("ar-EG", "Egypt");
        map.put("ar-IN", "India");
        map.put("ar-IQ", "Iraq");
        map.put("ar-JO", "Jordan");
        map.put("ar-KW", "Kuwait");
        map.put("ar-LB", "Lebanon");
        map.put("ar-LY", "Libya");
        map.put("ar-MA", "Morocco");
        map.put("ar-OM", "Oman");
        map.put("ar-QA", "Qatar");
        map.put("ar-SA", "Saudi Arabia");
        map.put("ar-SD", "Sudan");
        map.put("ar-SY", "Syrian Arab Republic");
        map.put("ar-TN", "Tunisia");
        map.put("ar-YE", "Yemen");
        map.put("as-IN", "India");
        map.put("ast-ES", "Spain");
        map.put("az-AZ", "Azerbaijan");
        map.put("be-BY", "Belarus");
        map.put("ber-DZ", "Algeria");
        map.put("ber-MA", "Morocco");
        map.put("bg-BG", "Bulgaria");
        map.put("bn-BD", "Bangladesh");
        map.put("bn-IN", "India");
        map.put("bo-CN", "China");
        map.put("bo-IN", "India");
        map.put("br-FR", "France");
        map.put("bs-BA", "Bosnia and Herzegovina");
        map.put("byn-ER", "Eritrea");
        map.put("ca-AD", "Andorra");
        map.put("ca-ES", "Spain");
        map.put("ca-FR", "France");
        map.put("ca-IT", "Italy");
        map.put("crh-UA", "Ukraine");
        map.put("cs-CZ", "Czech Republic");
        map.put("csb-PL", "Poland");
        map.put("cv-RU", "Russian Federation");
        map.put("cy-GB", "United Kingdom(Great Britain)");
        map.put("da-DK", "Denmark");
        map.put("de-AT", "Austria");
        map.put("de-BE", "Belgium");
        map.put("de-CH", "Switzerland");
        map.put("de-DE", "Germany");
        map.put("de-LU", "Luxembourg");
        map.put("dv-MV", "Maldives");
        map.put("dz-BT", "Bhutan");
        map.put("el-CY", "Cyprus");
        map.put("el-GR", "Greece");
        map.put("en-AG", "Antigua and Barbuda");
        map.put("en-AU", "Australia");
        map.put("en-BW", "Botswana");
        map.put("en-CA", "Canada");
        map.put("en-DK", "Denmark");
        map.put("en-GB", "United Kingdom(Great Britain)");
        map.put("en-HK", "Hong Kong");
        map.put("en-IE", "Ireland");
        map.put("en-IN", "India");
        map.put("en-NG", "Nigeria");
        map.put("en-NZ", "New Zealand");
        map.put("en-PH", "Philippines");
        map.put("en-SG", "Singapore");
        map.put("en-US", "United States of America(USA)");
        map.put("en-ZA", "South Africa");
        map.put("en-ZW", "Zimbabwe");
        map.put("es-AR", "Argentina");
        map.put("es-BO", "Bolivia");
        map.put("es-CL", "Chile");
        map.put("es-CO", "Colombia");
        map.put("es-CR", "Costa Rica");
        map.put("es-DO", "Dominican Republic");
        map.put("es-EC", "Ecuador");
        map.put("es-ES", "Spain");
        map.put("es-GT", "Guatemala");
        map.put("es-HN", "Honduras");
        map.put("es-MX", "Mexico");
        map.put("es-NI", "Nicaragua");
        map.put("es-PA", "Panama");
        map.put("es-PE", "Peru");
        map.put("es-PR", "Puerto Rico");
        map.put("es-PY", "Paraguay");
        map.put("es-SV", "El Salvador");
        map.put("es-US", "United States of America(USA)");
        map.put("es-UY", "Uruguay");
        map.put("es-VE", "Venezuela");
        map.put("et-EE", "Estonia");
        map.put("eu-ES", "Spain");
        map.put("fa-IR", "Iran, Islamic Republic of");
        map.put("fi-FI", "Finland");
        map.put("fil-PH", "Philippines");
        map.put("fo-FO", "Faroe Islands");
        map.put("fr-BE", "Belgium");
        map.put("fr-CA", "Canada");
        map.put("fr-CH", "Switzerland");
        map.put("fr-FR", "France");
        map.put("fr-LU", "Luxembourg");
        map.put("fur-IT", "Italy");
        map.put("fy-DE", "Germany");
        map.put("fy-NL", "Netherlands");
        map.put("ga-IE", "Ireland");
        map.put("gd-GB", "United Kingdom(Great Britain)");
        map.put("gez-ER", "Eritrea");
        map.put("gez-ET", "Ethiopia");
        map.put("gl-ES", "Spain");
        map.put("gu-IN", "India");
        map.put("gv-GB", "United Kingdom(Great Britain)");
        map.put("ha-NG", "Nigeria");
        map.put("he-IL", "Israel");
        map.put("hi-IN", "India");
        map.put("hne-IN", "India");
        map.put("hr-HR", "Croatia");
        map.put("hsb-DE", "Germany");
        map.put("ht-HT", "Haiti");
        map.put("hu-HU", "Hungary");
        map.put("hy-AM", "Armenia");
        map.put("id-ID", "Indonesia");
        map.put("ig-NG", "Nigeria");
        map.put("ik-CA", "Canada");
        map.put("is-IS", "Iceland");
        map.put("it-CH", "Switzerland");
        map.put("it-IT", "Italy");
        map.put("iu-CA", "Canada");
        map.put("iw-IL", "Israel");
        map.put("ja-JP", "Japan");
        map.put("ka-GE", "Georgia");
        map.put("kk-KZ", "Kazakhstan");
        map.put("kl-GL", "Greenland");
        map.put("km-KH", "Cambodia");
        map.put("kn-IN", "India");
        map.put("ko-KR", "South Korea");
        map.put("kok-IN", "India");
        map.put("ks-IN", "India");
        map.put("ku-TR", "Turkey");
        map.put("kw-GB", "United Kingdom(Great Britain)");
        map.put("ky-KG", "Kyrgyzstan");
        map.put("lg-UG", "Uganda");
        map.put("li-BE", "Belgium");
        map.put("li-NL", "Netherlands");
        map.put("lo-LA", "Lao People\"s Democratic Republic");
        map.put("lt-LT", "Lithuania");
        map.put("lv-LV", "Latvia");
        map.put("mai-IN", "India");
        map.put("mg-MG", "Madagascar");
        map.put("mi-NZ", "New Zealand");
        map.put("mk-MK", "Macedonia, the Former Yugoslav Republic of");
        map.put("ml-IN", "India");
        map.put("mn-MN", "Mongolia");
        map.put("mr-IN", "India");
        map.put("ms-MY", "Malaysia");
        map.put("mt-MT", "Malta");
        map.put("my-MM", "Myanmar");
        map.put("nb-NO", "Norway");
        map.put("nds-DE", "Germany");
        map.put("nds-NL", "Netherlands");
        map.put("ne-NP", "Nepal");
        map.put("nl-AW", "Aruba");
        map.put("nl-BE", "Belgium");
        map.put("nl-NL", "Netherlands");
        map.put("nn-NO", "Norway");
        map.put("no-NO", "Norway");
        map.put("nr-ZA", "South Africa");
        map.put("nso-ZA", "South Africa");
        map.put("oc-FR", "France");
        map.put("om-ET", "Ethiopia");
        map.put("om-KE", "Kenya");
        map.put("or-IN", "India");
        map.put("pa-IN", "India");
        map.put("pa-PK", "Pakistan");
        map.put("pl-PL", "Poland");
        map.put("ps-AF", "Afghanistan");
        map.put("pt-BR", "Brazil");
        map.put("pt-PT", "Portugal");
        map.put("ro-RO", "Romania");
        map.put("ru-RU", "Russian Federation");
        map.put("ru-UA", "Ukraine");
        map.put("rw-RW", "Rwanda");
        map.put("sa-IN", "India");
        map.put("sc-IT", "Italy");
        map.put("sd-IN", "India");
        map.put("se-NO", "Norway");
        map.put("shs-CA", "Canada");
        map.put("si-LK", "Sri Lanka");
        map.put("sid-ET", "Ethiopia");
        map.put("sk-SK", "Slovakia");
        map.put("sl-SI", "Slovenia");
        map.put("so-DJ", "Djibouti");
        map.put("so-ET", "Ethiopia");
        map.put("so-KE", "Kenya");
        map.put("so-SO", "Somalia");
        map.put("sq-AL", "Albania");
        map.put("sq-MK", "Macedonia, the Former Yugoslav Republic of");
        map.put("sr-ME", "Montenegro");
        map.put("sr-RS", "Serbia");
        map.put("ss-ZA", "South Africa");
        map.put("st-ZA", "South Africa");
        map.put("sv-FI", "Finland");
        map.put("sv-SE", "Sweden");
        map.put("ta-IN", "India");
        map.put("te-IN", "India");
        map.put("tg-TJ", "Tajikistan");
        map.put("th-TH", "Thailand");
        map.put("ti-ER", "Eritrea");
        map.put("ti-ET", "Ethiopia");
        map.put("tig-ER", "Eritrea");
        map.put("tk-TM", "Turkmenistan");
        map.put("tl-PH", "Philippines");
        map.put("tn-ZA", "South Africa");
        map.put("tr-CY", "Cyprus");
        map.put("tr-TR", "Turkey");
        map.put("ts-ZA", "South Africa");
        map.put("tt-RU", "Russian Federation");
        map.put("ug-CN", "China");
        map.put("uk-UA", "Ukraine");
        map.put("ur-PK", "Pakistan");
        map.put("uz-UZ", "Uzbekistan");
        map.put("ve-ZA", "South Africa");
        map.put("vi-VN", "Viet Nam");
        map.put("wa-BE", "Belgium");
        map.put("wo-SN", "Senegal");
        map.put("xh-ZA", "South Africa");
        map.put("yi-US", "United States of America(USA)");
        map.put("yo-NG", "Nigeria");
        map.put("zh-CN", "China");
        map.put("zh-HK", "Hong Kong");
        map.put("zh-SG", "Singapore");
        map.put("zh-TW", "Taiwan, Province of China");
        map.put("zu-ZA", "South Africa");


		map.put("aa_DJ", "Djibouti");
		map.put("aa_ER", "Eritrea");
		map.put("aa_ET", "Ethiopia");
		map.put("af_ZA", "South Africa");
		map.put("am_ET", "Ethiopia");
		map.put("an_ES", "Spain");
		map.put("ar_AE", "United Arab Emirates");
		map.put("ar_BH", "Bahrain");
		map.put("ar_DZ", "Algeria");
		map.put("ar_EG", "Egypt");
		map.put("ar_IN", "India");
		map.put("ar_IQ", "Iraq");
		map.put("ar_JO", "Jordan");
		map.put("ar_KW", "Kuwait");
		map.put("ar_LB", "Lebanon");
		map.put("ar_LY", "Libya");
		map.put("ar_MA", "Morocco");
		map.put("ar_OM", "Oman");
		map.put("ar_QA", "Qatar");
		map.put("ar_SA", "Saudi Arabia");
		map.put("ar_SD", "Sudan");
		map.put("ar_SY", "Syrian Arab Republic");
		map.put("ar_TN", "Tunisia");
		map.put("ar_YE", "Yemen");
		map.put("as_IN", "India");
		map.put("ast_ES", "Spain");
		map.put("az_AZ", "Azerbaijan");
		map.put("be_BY", "Belarus");
		map.put("ber_DZ", "Algeria");
		map.put("ber_MA", "Morocco");
		map.put("bg_BG", "Bulgaria");
		map.put("bn_BD", "Bangladesh");
		map.put("bn_IN", "India");
		map.put("bo_CN", "China");
		map.put("bo_IN", "India");
		map.put("br_FR", "France");
		map.put("bs_BA", "Bosnia and Herzegovina");
		map.put("byn_ER", "Eritrea");
		map.put("ca_AD", "Andorra");
		map.put("ca_ES", "Spain");
		map.put("ca_FR", "France");
		map.put("ca_IT", "Italy");
		map.put("crh_UA", "Ukraine");
		map.put("cs_CZ", "Czech Republic");
		map.put("csb_PL", "Poland");
		map.put("cv_RU", "Russian Federation");
		map.put("cy_GB", "United Kingdom(Great Britain)");
		map.put("da_DK", "Denmark");
		map.put("de_AT", "Austria");
		map.put("de_BE", "Belgium");
		map.put("de_CH", "Switzerland");
		map.put("de_DE", "Germany");
		map.put("de_LU", "Luxembourg");
		map.put("dv_MV", "Maldives");
		map.put("dz_BT", "Bhutan");
		map.put("el_CY", "Cyprus");
		map.put("el_GR", "Greece");
		map.put("en_AG", "Antigua and Barbuda");
		map.put("en_AU", "Australia");
		map.put("en_BW", "Botswana");
		map.put("en_CA", "Canada");
		map.put("en_DK", "Denmark");
		map.put("en_GB", "United Kingdom(Great Britain)");
		map.put("en_HK", "Hong Kong");
		map.put("en_IE", "Ireland");
		map.put("en_IN", "India");
		map.put("en_NG", "Nigeria");
		map.put("en_NZ", "New Zealand");
		map.put("en_PH", "Philippines");
		map.put("en_SG", "Singapore");
		map.put("en_US", "United States of America(USA)");
		map.put("en_ZA", "South Africa");
		map.put("en_ZW", "Zimbabwe");
		map.put("es_AR", "Argentina");
		map.put("es_BO", "Bolivia");
		map.put("es_CL", "Chile");
		map.put("es_CO", "Colombia");
		map.put("es_CR", "Costa Rica");
		map.put("es_DO", "Dominican Republic");
		map.put("es_EC", "Ecuador");
		map.put("es_ES", "Spain");
		map.put("es_GT", "Guatemala");
		map.put("es_HN", "Honduras");
		map.put("es_MX", "Mexico");
		map.put("es_NI", "Nicaragua");
		map.put("es_PA", "Panama");
		map.put("es_PE", "Peru");
		map.put("es_PR", "Puerto Rico");
		map.put("es_PY", "Paraguay");
		map.put("es_SV", "El Salvador");
		map.put("es_US", "United States of America(USA)");
		map.put("es_UY", "Uruguay");
		map.put("es_VE", "Venezuela");
		map.put("et_EE", "Estonia");
		map.put("eu_ES", "Spain");
		map.put("fa_IR", "Iran, Islamic Republic of");
		map.put("fi_FI", "Finland");
		map.put("fil_PH", "Philippines");
		map.put("fo_FO", "Faroe Islands");
		map.put("fr_BE", "Belgium");
		map.put("fr_CA", "Canada");
		map.put("fr_CH", "Switzerland");
		map.put("fr_FR", "France");
		map.put("fr_LU", "Luxembourg");
		map.put("fur_IT", "Italy");
		map.put("fy_DE", "Germany");
		map.put("fy_NL", "Netherlands");
		map.put("ga_IE", "Ireland");
		map.put("gd_GB", "United Kingdom(Great Britain)");
		map.put("gez_ER", "Eritrea");
		map.put("gez_ET", "Ethiopia");
		map.put("gl_ES", "Spain");
		map.put("gu_IN", "India");
		map.put("gv_GB", "United Kingdom(Great Britain)");
		map.put("ha_NG", "Nigeria");
		map.put("he_IL", "Israel");
		map.put("hi_IN", "India");
		map.put("hne_IN", "India");
		map.put("hr_HR", "Croatia");
		map.put("hsb_DE", "Germany");
		map.put("ht_HT", "Haiti");
		map.put("hu_HU", "Hungary");
		map.put("hy_AM", "Armenia");
		map.put("id_ID", "Indonesia");
		map.put("ig_NG", "Nigeria");
		map.put("ik_CA", "Canada");
		map.put("is_IS", "Iceland");
		map.put("it_CH", "Switzerland");
		map.put("it_IT", "Italy");
		map.put("iu_CA", "Canada");
		map.put("iw_IL", "Israel");
		map.put("ja_JP", "Japan");
		map.put("ka_GE", "Georgia");
		map.put("kk_KZ", "Kazakhstan");
		map.put("kl_GL", "Greenland");
		map.put("km_KH", "Cambodia");
		map.put("kn_IN", "India");
		map.put("ko_KR", "South Korea");
		map.put("kok_IN", "India");
		map.put("ks_IN", "India");
		map.put("ku_TR", "Turkey");
		map.put("kw_GB", "United Kingdom(Great Britain)");
		map.put("ky_KG", "Kyrgyzstan");
		map.put("lg_UG", "Uganda");
		map.put("li_BE", "Belgium");
		map.put("li_NL", "Netherlands");
		map.put("lo_LA", "Lao People\"s Democratic Republic");
		map.put("lt_LT", "Lithuania");
		map.put("lv_LV", "Latvia");
		map.put("mai_IN", "India");
		map.put("mg_MG", "Madagascar");
		map.put("mi_NZ", "New Zealand");
		map.put("mk_MK", "Macedonia, the Former Yugoslav Republic of");
		map.put("ml_IN", "India");
		map.put("mn_MN", "Mongolia");
		map.put("mr_IN", "India");
		map.put("ms_MY", "Malaysia");
		map.put("mt_MT", "Malta");
		map.put("my_MM", "Myanmar");
		map.put("nb_NO", "Norway");
		map.put("nds_DE", "Germany");
		map.put("nds_NL", "Netherlands");
		map.put("ne_NP", "Nepal");
		map.put("nl_AW", "Aruba");
		map.put("nl_BE", "Belgium");
		map.put("nl_NL", "Netherlands");
		map.put("nn_NO", "Norway");
		map.put("no_NO", "Norway");
		map.put("nr_ZA", "South Africa");
		map.put("nso_ZA", "South Africa");
		map.put("oc_FR", "France");
		map.put("om_ET", "Ethiopia");
		map.put("om_KE", "Kenya");
		map.put("or_IN", "India");
		map.put("pa_IN", "India");
		map.put("pa_PK", "Pakistan");
		map.put("pl_PL", "Poland");
		map.put("ps_AF", "Afghanistan");
		map.put("pt_BR", "Brazil");
		map.put("pt_PT", "Portugal");
		map.put("ro_RO", "Romania");
		map.put("ru_RU", "Russian Federation");
		map.put("ru_UA", "Ukraine");
		map.put("rw_RW", "Rwanda");
		map.put("sa_IN", "India");
		map.put("sc_IT", "Italy");
		map.put("sd_IN", "India");
		map.put("se_NO", "Norway");
		map.put("shs_CA", "Canada");
		map.put("si_LK", "Sri Lanka");
		map.put("sid_ET", "Ethiopia");
		map.put("sk_SK", "Slovakia");
		map.put("sl_SI", "Slovenia");
		map.put("so_DJ", "Djibouti");
		map.put("so_ET", "Ethiopia");
		map.put("so_KE", "Kenya");
		map.put("so_SO", "Somalia");
		map.put("sq_AL", "Albania");
		map.put("sq_MK", "Macedonia, the Former Yugoslav Republic of");
		map.put("sr_ME", "Montenegro");
		map.put("sr_RS", "Serbia");
		map.put("ss_ZA", "South Africa");
		map.put("st_ZA", "South Africa");
		map.put("sv_FI", "Finland");
		map.put("sv_SE", "Sweden");
		map.put("ta_IN", "India");
		map.put("te_IN", "India");
		map.put("tg_TJ", "Tajikistan");
		map.put("th_TH", "Thailand");
		map.put("ti_ER", "Eritrea");
		map.put("ti_ET", "Ethiopia");
		map.put("tig_ER", "Eritrea");
		map.put("tk_TM", "Turkmenistan");
		map.put("tl_PH", "Philippines");
		map.put("tn_ZA", "South Africa");
		map.put("tr_CY", "Cyprus");
		map.put("tr_TR", "Turkey");
		map.put("ts_ZA", "South Africa");
		map.put("tt_RU", "Russian Federation");
		map.put("ug_CN", "China");
		map.put("uk_UA", "Ukraine");
		map.put("ur_PK", "Pakistan");
		map.put("uz_UZ", "Uzbekistan");
		map.put("ve_ZA", "South Africa");
		map.put("vi_VN", "Viet Nam");
		map.put("wa_BE", "Belgium");
		map.put("wo_SN", "Senegal");
		map.put("xh_ZA", "South Africa");
		map.put("yi_US", "United States of America(USA)");
		map.put("yo_NG", "Nigeria");
		map.put("zh_CN", "China");
		map.put("zh_HK", "Hong Kong");
		map.put("zh_SG", "Singapore");
		map.put("zh_TW", "Taiwan, Province of China");
		map.put("zu_ZA", "South Africa");

		Set<String> set = map.keySet();

		Iterator<String> iterator = set.iterator();

		while(iterator.hasNext()) {
			String charset = iterator.next();
			String charsetL = (charset.toLowerCase());
			String value = map.get(charset);
			System.out.println("map.put(\"" + charsetL + "\", \"" + value + "\");" );


		}

	}

}
